//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tbl
    {
        public string Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Phone { get; set; }
        public string Emp_Email { get; set; }
    }
}
